spring:
  flyway:
    enabled: true  # Flyway 활성화
    baseline-on-migrate: true  # 기존 DB에서도 마이그레이션 실행 가능
    validate-on-migrate: true  # 마이그레이션 파일 유효성 검증
    locations: classpath:db/migration  # SQL 파일이 위치한 폴더

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: none  # Hibernate가 테이블을 생성하지 않도록 설정
        show_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true  # Flyway가 먼저 실행된 후 데이터 소스를 초기화

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.17:3306/BooglePlus?serverTimezone=UTC&characterEncoding=UTF-8
    username: boogleplus
    password: '00000000'
    hikari:
      connection-timeout: 30000

decorator:
  datasource:
    p6spy:
      enable-logging: true  # SQL 로그 기록 활성화

logging:
  level:
    root: INFO
    org.springframework: INFO
  file:
    path: ./logs
    name: log
  logback:
    rollingpolicy:
      max-history: 20
      total-size-cap: 100MB
      max-file-size: 10MB

aladin:
  api:
    ttb-key: ENC(Jem/KbwMCD0y1OKbM+9vWzVpE116xZfxVl2kRL1YYUoqFUjYnoZ3Tw==)
    output: js
    version: 20131101
    book-list.url: http://www.aladin.co.kr/ttb/api/ItemList.aspx
    book-detail.url: http://www.aladin.co.kr/ttb/api/ItemLookUp.aspx