ALTER TABLE BOOK
    ADD PRIMARY KEY (id);

ALTER TABLE BOOK_REPORT
    ADD PRIMARY KEY (id);

ALTER TABLE MEMBER
    ADD PRIMARY KEY (id);

ALTER TABLE MEMBER_INFLOW
    ADD PRIMARY KEY (id);

ALTER TABLE MEMBER_REPLY
    ADD PRIMARY KEY (id);

ALTER TABLE REPLY
    ADD PRIMARY KEY (id);

DROP TABLE BATCH_JOB_EXECUTION;

DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;

DROP TABLE BATCH_JOB_EXECUTION_PARAMS;

DROP TABLE BATCH_JOB_EXECUTION_SEQ;

DROP TABLE BATCH_JOB_INSTANCE;

DROP TABLE BATCH_JOB_SEQ;

DROP TABLE BATCH_STEP_EXECUTION;

DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;

DROP TABLE BATCH_STEP_EXECUTION_SEQ;

ALTER TABLE MEMBER_INFLOW
    DROP COLUMN column_name;

ALTER TABLE MEMBER_INFLOW
    DROP COLUMN column_name2;

ALTER TABLE BOOK
    MODIFY author VARCHAR(255);

ALTER TABLE BOOK_REPORT
    DROP COLUMN book_id;

ALTER TABLE BOOK_REPORT
    DROP COLUMN created_at;

ALTER TABLE BOOK_REPORT
    DROP COLUMN id;

ALTER TABLE BOOK_REPORT
    DROP COLUMN last_modified_at;

ALTER TABLE BOOK_REPORT
    DROP COLUMN member_id;

ALTER TABLE BOOK_REPORT
    ADD book_id BIGINT NOT NULL;

ALTER TABLE BOOK_REPORT
    ADD CONSTRAINT FK_BOOK_REPORT_ON_BOOK FOREIGN KEY (book_id) REFERENCES BOOK (id);

ALTER TABLE BOOK_REPORT
    MODIFY book_id BIGINT NOT NULL;

ALTER TABLE REPLY
    DROP COLUMN book_report_id;

ALTER TABLE REPLY
    DROP COLUMN created_at;

ALTER TABLE REPLY
    DROP COLUMN id;

ALTER TABLE REPLY
    DROP COLUMN last_modified_at;

ALTER TABLE REPLY
    DROP COLUMN member_id;

ALTER TABLE REPLY
    DROP COLUMN parent_reply_id;

ALTER TABLE REPLY
    ADD book_report_id BIGINT NOT NULL;

ALTER TABLE REPLY
    ADD CONSTRAINT FK_REPLY_ON_BOOK_REPORT FOREIGN KEY (book_report_id) REFERENCES BOOK_REPORT (id);

ALTER TABLE REPLY
    MODIFY book_report_id BIGINT NOT NULL;

ALTER TABLE BOOK
    DROP COLUMN category_id;

ALTER TABLE BOOK
    DROP COLUMN created_at;

ALTER TABLE BOOK
    DROP COLUMN id;

ALTER TABLE BOOK
    DROP COLUMN isbn;

ALTER TABLE BOOK
    DROP COLUMN last_modified_at;

ALTER TABLE BOOK
    DROP COLUMN publish_date;

ALTER TABLE BOOK
    DROP COLUMN sales_price;

ALTER TABLE BOOK
    ADD category_id BIGINT NULL;

ALTER TABLE BOOK_REPORT
    MODIFY content VARCHAR(255);

ALTER TABLE BOOK_REPORT
    MODIFY content VARCHAR(255) NOT NULL;

ALTER TABLE REPLY
    MODIFY content VARCHAR(255);

ALTER TABLE REPLY
    MODIFY content VARCHAR(255) NOT NULL;

ALTER TABLE BOOK
    ADD created_at datetime NULL;

ALTER TABLE BOOK_REPORT
    ADD created_at datetime NULL;

ALTER TABLE REPLY
    ADD created_at datetime NULL;

ALTER TABLE BOOK
    MODIFY created_by VARCHAR(255);

ALTER TABLE BOOK
    MODIFY created_by VARCHAR(255) NOT NULL;

ALTER TABLE BOOK_REPORT
    MODIFY created_by VARCHAR(255);

ALTER TABLE BOOK
    MODIFY `description` VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY email VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY email VARCHAR(255) NOT NULL;

ALTER TABLE BOOK
    ADD id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY;

ALTER TABLE BOOK
    MODIFY id BIGINT NOT NULL;

ALTER TABLE BOOK
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE BOOK_REPORT
    ADD id BIGINT NOT NULL PRIMARY KEY;

ALTER TABLE BOOK_REPORT
    MODIFY id BIGINT NOT NULL;

ALTER TABLE MEMBER
    DROP COLUMN id;

ALTER TABLE MEMBER
    DROP COLUMN last_modified_at;

ALTER TABLE MEMBER
    DROP COLUMN signup_date;

ALTER TABLE MEMBER
    DROP COLUMN withdrawal_date;

ALTER TABLE MEMBER
    ADD id BIGINT NOT NULL PRIMARY KEY;

ALTER TABLE MEMBER
    MODIFY id BIGINT NOT NULL;

ALTER TABLE MEMBER_INFLOW
    DROP COLUMN id;

ALTER TABLE MEMBER_INFLOW
    ADD id BIGINT NOT NULL PRIMARY KEY;

ALTER TABLE MEMBER_INFLOW
    MODIFY id BIGINT NOT NULL;

ALTER TABLE MEMBER_REPLY
    DROP COLUMN id;

ALTER TABLE MEMBER_REPLY
    DROP COLUMN member_id;

ALTER TABLE MEMBER_REPLY
    DROP COLUMN record_date;

ALTER TABLE MEMBER_REPLY
    ADD id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY;

ALTER TABLE MEMBER_REPLY
    MODIFY id BIGINT NOT NULL;

ALTER TABLE MEMBER_REPLY
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE REPLY
    ADD id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY;

ALTER TABLE REPLY
    MODIFY id BIGINT NOT NULL;

ALTER TABLE REPLY
    MODIFY id BIGINT AUTO_INCREMENT;

ALTER TABLE MEMBER_INFLOW
    MODIFY inflow INT NOT NULL;

ALTER TABLE BOOK_REPORT
    MODIFY is_public VARCHAR(255);

ALTER TABLE BOOK_REPORT
    MODIFY is_public VARCHAR(255) NOT NULL;

ALTER TABLE BOOK
    ADD isbn BIGINT NULL;

ALTER TABLE BOOK
    ADD last_modified_at datetime NULL;

ALTER TABLE BOOK_REPORT
    ADD last_modified_at datetime NULL;

ALTER TABLE MEMBER
    ADD last_modified_at datetime NULL;

ALTER TABLE REPLY
    ADD last_modified_at datetime NULL;

ALTER TABLE BOOK
    MODIFY last_modified_by VARCHAR(255);

ALTER TABLE BOOK_REPORT
    MODIFY last_modified_by VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY last_modified_by VARCHAR(255);

ALTER TABLE BOOK_REPORT
    ADD member_id BIGINT NOT NULL;

ALTER TABLE BOOK_REPORT
    ADD CONSTRAINT FK_BOOK_REPORT_ON_MEMBER FOREIGN KEY (member_id) REFERENCES MEMBER (id);

ALTER TABLE BOOK_REPORT
    MODIFY member_id BIGINT NOT NULL;

ALTER TABLE MEMBER_REPLY
    ADD member_id BIGINT NOT NULL;

ALTER TABLE MEMBER_REPLY
    MODIFY member_id BIGINT NOT NULL;

ALTER TABLE REPLY
    ADD member_id BIGINT NOT NULL;

ALTER TABLE REPLY
    ADD CONSTRAINT FK_REPLY_ON_MEMBER FOREIGN KEY (member_id) REFERENCES MEMBER (id);

ALTER TABLE REPLY
    MODIFY member_id BIGINT NOT NULL;

ALTER TABLE MEMBER_INFLOW
    MODIFY month INT NOT NULL;

ALTER TABLE MEMBER
    MODIFY name VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY name VARCHAR(255) NOT NULL;

ALTER TABLE MEMBER
    MODIFY nickname VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY nickname VARCHAR(255) NOT NULL;

ALTER TABLE REPLY
    ADD parent_reply_id BIGINT NULL;

ALTER TABLE MEMBER
    MODIFY password VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY password VARCHAR(255) NOT NULL;

ALTER TABLE MEMBER
    MODIFY phone_number VARCHAR(255);

ALTER TABLE BOOK
    ADD publish_date date NULL;

ALTER TABLE BOOK
    MODIFY publisher VARCHAR(255);

ALTER TABLE MEMBER_REPLY
    ADD record_date date NOT NULL;

ALTER TABLE MEMBER_REPLY
    MODIFY record_date date NOT NULL;

ALTER TABLE MEMBER_REPLY
    MODIFY reply_count INT NOT NULL;

ALTER TABLE MEMBER_REPLY
    MODIFY reply_rank INT NOT NULL;

ALTER TABLE MEMBER
    MODIFY `role` VARCHAR(255);

ALTER TABLE MEMBER
    MODIFY `role` VARCHAR(255) NOT NULL;

ALTER TABLE BOOK
    ADD sales_price INT NULL;

ALTER TABLE MEMBER
    ADD signup_date datetime NULL;

ALTER TABLE BOOK
    MODIFY thumbnail_url VARCHAR(255);

ALTER TABLE BOOK
    MODIFY title VARCHAR(255);

ALTER TABLE BOOK_REPORT
    MODIFY title VARCHAR(255);

ALTER TABLE BOOK_REPORT
    MODIFY title VARCHAR(255) NOT NULL;

ALTER TABLE MEMBER_INFLOW
    MODIFY week INT NOT NULL;

ALTER TABLE MEMBER
    ADD withdrawal_date datetime NULL;

ALTER TABLE MEMBER_INFLOW
    MODIFY year INT NOT NULL;